# Default values for generic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

service:
  type: ClusterIP
  port: 80

## NGINX Ingress controller
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/issuer: "nameOfIssuer"
    # cert-manager.io/cluster-issuer: "nameOfClusterIssuer"
  hosts: []
    #- host: chart-example.local
    #  paths: 
    #    - /     
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## istio service mesh
istio:
  enabled: false
  dnsNames: 
    - chart-example.local
  tls: 
    enabled: false
    ## localCert = true secret with certificate and private key must be defined in credentialName
    ## localCert = false certificate and private key is expected to be attached to Load Balancer
    localCert: true
    credentialName: mydomain-tls
  certManager:
    enabled: false
    issuer:
      name: letsencrypt-prod
      kind: ClusterIssuer
  gateway:
    enabled: false
    httpsRedirect: false
    http: false
  virtualservice:
    gateways: []
      #- istio-system/my-gateway-example
    paths: 
      - /
    

resources: 
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 10Mi

containerPort: 8080

readinessProbe:
#  failureThreshold: 5
#  httpGet:
#    path: /api/health
#    port: http
#    scheme: HTTP
#  initialDelaySeconds: 60
#  periodSeconds: 10
#  successThreshold: 1
#  timeoutSeconds: 1


livenessProbe: 
#  failureThreshold: 5
#  httpGet:
#    path: /api/health
#    port: http
#    scheme: HTTP
#  initialDelaySeconds: 60
#  periodSeconds: 10
#  successThreshold: 1
#  timeoutSeconds: 1
  


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80






