# openapi2-run.yaml
swagger: '2.0'
info:
  title: Books api
  description: Books API on API Gateway with a Cloud Run backend
  version: 1.0.0
## only for cloud endpoints 
#host: books-fm37xyhdfa-rj.a.run.app
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://books-fm37xyhdfa-rj.a.run.app
x-google-management:
  metrics:
    - name: read-requests
      displayName: Read requests
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: read-requests-limit
        metric: read-requests
        unit: 1/min/{project}
        values:
          STANDARD: 5     
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"             
paths:
  /api/books/{bookId}:
    get:
      parameters:
        - in: path
          name: bookId
          required: true
          type: string
          description: Book id
      summary: Return a book
      operationId: getBook
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      x-google-quota:
        metricCosts:
          "read-requests": 1
      security:
      - api_key: []
  /api/books:
    get:
      summary: Return all books
      operationId: getAllBooks
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      x-google-quota:
        metricCosts:
          "read-requests": 1            
      security:
      - api_key: []
  /api/health:
    get:
      summary: Return books health status
      operationId: getBooksHealth
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      x-google-quota:
        metricCosts:
          "read-requests": 1            
      security: []
  /api/outboundip:
    get:
      summary: Return books api outbound ip
      operationId: getBooksOutBoundIp
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      x-google-quota:
        metricCosts:
          "read-requests": 1            
      security: []