apiVersion: v1
kind: Service
metadata:
  name: books
  namespace: default
  labels:
      app: books
      version: v1.1.0
spec:
  type: ClusterIP
  selector:
    app: books
    version: v1.1.0
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
